Add "ca-certificates" to install in monit
To avoid these errors:
ERROR: The certificate of `github.com' is not trusted.
ERROR: The certificate of `github.com' hasn't got a known issuer.
We need to have a valid local SSL trusted store. This can be fixed by installing ca-certificates package which will download/install well-known trusted SSL certificates of CAs.